#define MAIN_WINDOW_NAME "poots"
#define FRAMES_PER_SECOND 15
#define MAX_VELOCITY 20
#define VELOCITY 10
#define STEP_X 10
#define STEP_Y 10
#define STEP_V 5
#define STEP_A 5
#define SPRITE_BG_WIDTH 5
#define SPRITE_BG_HEIGHT 5
#define SPRITE_ITERATIONS 1
